version: '3'

services:
  
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    ports: 
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    container_name: sqlite3_container
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      #Modify following line
      - ./.docker/dbdata:/root/db/
      - ./.docker/sqlite:/docker-entrypoint-initdb.d
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    restart: always